/* eslint-disable */
export const activities = [
    {
        id          : 'cd5fa417-b667-482d-b208-798d9da3213c',
        customer_picture : 'assets/images/avatars/male-01.jpg',
        status      : 'Awaiting',
        name        : 'Sergio Peralta',
        customer    : 'Dejesus Michael',
        pass_date   : '2023-01-10T12:00:00.000Z',
        companyId   : 'cd5fa417-b667-482d-b208-198d9da3213c',
        address     : '279 Independence Avenue, Calvary, Guam, PO4127',
        notes       : '<p>Do incididunt cillum duis eu pariatur enim proident minim officia amet proident consequat consequat qui consequat magna magna occaecat aliquip culpa pariatur velit nisi nostrud irure eu ullamco exercitation sint.</p><p>Cillum deserunt laborum laborum quis nisi enim et aliquip labore excepteur in excepteur labore amet in ipsum ipsum nostrud deserunt lorem nisi voluptate dolor minim enim ut eu cupidatat enim.</p>',
    },
    {
        id          : 'beec5287-ed50-4504-858a-5dc3f8ce6935',
        customer_picture : 'assets/images/avatars/male-01.jpg',
        status      : 'inside_of_building',
        name        : 'Kesia Peralta',
        customer    : 'Dejesus Michael',
        title       : 'Weather Analyst',
        companyId   : 'beec5287-ed50-4504-858a-56c3f8ce6935',
        pass_date   : '1994-12-05T12:00:00.000Z',
        address     : '856 Woodside Avenue, Alfarata, Iowa, PO4992',
        notes       : '<p>Consequat duis ullamco sint elit pariatur esse dolore nostrud consequat lorem duis sunt veniam ipsum exercitation eiusmod consequat nisi quis voluptate quis officia irure fugiat ex duis eu amet ex.</p><p>Irure est nisi dolor culpa sunt nulla irure lorem adipisicing non do consequat deserunt et ea eu non reprehenderit fugiat ex elit nulla sunt quis voluptate enim nulla aliquip veniam.</p>',
    },
    {
        id          : 'beec5287-ed50-4504-858a-5dc3f8ce6935',
        customer_picture : 'assets/images/avatars/male-01.jpg',
        status      : 'inside_of_building',
        name        : 'Megan Ramos',
        customer    : 'Jose Juarez',
        title       : 'Weather Analyst',
        companyId   : 'beec5287-ed50-4504-858a-56c3f8ce6935',
        pass_date   : '1999-12-05T12:00:00.000Z',
        address     : '856 Woodside Avenue, Alfarata, Iowa, PO4992',
        notes       : '<p>Consequat duis ullamco sint elit pariatur esse dolore nostrud consequat lorem duis sunt veniam ipsum exercitation eiusmod consequat nisi quis voluptate quis officia irure fugiat ex duis eu amet ex.</p><p>Irure est nisi dolor culpa sunt nulla irure lorem adipisicing non do consequat deserunt et ea eu non reprehenderit fugiat ex elit nulla sunt quis voluptate enim nulla aliquip veniam.</p>',
    },
    {
        id          : '9d3f0e7f-dcbd-4e56-a5e8-87b8154e9edf',
        customer_picture : 'assets/images/avatars/male-02.jpg',
        status      : 'Awaiting',
        name        : 'Bradley Sanchez',
        customer    : 'Daniel Fernandez',
        pass_date   : '1988-05-26T12:00:00.000Z',
        companyId   : 'beec5287-ed50-4504-858a-56c3f8ce6935',
        address     : '943 Adler Place, Hamilton, South Dakota, PO5592',
        notes       : '<p>Est amet in adipisicing ex excepteur ullamco est lorem adipisicing veniam reprehenderit elit commodo cillum commodo eu officia fugiat id reprehenderit sunt mollit eiusmod dolor fugiat ad do esse aliquip.</p><p>Mollit amet adipisicing enim est est commodo sint et eu nulla in laboris ipsum aliqua elit aliqua adipisicing ea nulla nulla consectetur velit laborum labore ullamco eu sit consectetur velit.</p>',
    },
    {
        id          : '42a5da95-5e6d-42fd-a09d-de755d123a47',
        customer_picture : 'assets/images/avatars/male-01.jpg',
        status      : 'inside of building',
        name        : 'Maria Perez',
        customer    : 'Cesar Mendez',
        title       : 'Electromedical Equipment Technician',
        companyId   : 'beec5287-ed50-4504-858a-56c3f8ce6935',
        pass_date   : '1988-05-26T12:00:00.000Z',
        address     : 'Residencial Costa mar',
         
    },
    {
        id          : 'cd5fa417-b667-482d-b208-798d9da3213c',
        customer_picture : 'assets/images/avatars/male-01.jpg',
        status      : 'inside of building',
        name        : 'Marilyn Peralta',
        customer    : 'Joseph Michael',
        pass_date   : '2023-01-10T12:00:00.000Z',
        companyId   : 'cd5fa417-b667-482d-b208-198d9da3213c',
        address     : '279 Independence Avenue, Calvary, Guam, PO4127',
        notes       : '<p>Do incididunt cillum duis eu pariatur enim proident minim officia amet proident consequat consequat qui consequat magna magna occaecat aliquip culpa pariatur velit nisi nostrud irure eu ullamco exercitation sint.</p><p>Cillum deserunt laborum laborum quis nisi enim et aliquip labore excepteur in excepteur labore amet in ipsum ipsum nostrud deserunt lorem nisi voluptate dolor minim enim ut eu cupidatat enim.</p>',
    },
    {
        id          : 'a7806ced-03f1-4197-8b30-00bdd463366b',
        customer_picture : 'assets/images/avatars/male-04.jpg',
        status      : 'Awaiting',
        name        : 'Marsh Cochran',
        customer    : 'Bradley Sanchez',
        pass_date   : '1983-12-22T12:00:00.000Z',
        companyId   : 'a7806ced-03f1-4197-8b30-00bdd4633664',
        address     : '487 Hamilton Walk, Bergoo, American Samoa, PO5616',
        notes       : '<p>Id eiusmod deserunt amet lorem commodo consequat nostrud magna aliquip ex et pariatur labore non elit ad ad nulla culpa reprehenderit enim magna aliqua enim pariatur occaecat sint do lorem.</p><p>Adipisicing ut est nulla nisi cupidatat consequat aliqua et esse in voluptate amet eiusmod ut esse ea do irure commodo aute culpa amet consequat id adipisicing et incididunt ut duis.</p>',
    },
    {
        id          : 'f4ad15d9-5a24-463a-88ea-6189d6bb3a53',
        customer_picture : 'assets/images/avatars/male-05.jpg',
        status      : 'Awaiting',
        name        : 'Parrish Austin',
        customer    : 'Mario Flores',
        pass_date   : '1963-08-24T12:00:00.000Z',
        companyId   : 'a7806ced-03f1-4197-8b30-00bdd4243664',
        address     : '610 Harbor Lane, Cascades, Minnesota, PO8639',
        notes       : '<p>Cillum enim eiusmod dolor aliqua ipsum exercitation sint aliqua lorem dolore id velit sint velit labore cupidatat minim cupidatat elit est magna eu proident eiusmod non pariatur est esse pariatur.</p><p>Sint do enim officia velit pariatur excepteur commodo adipisicing labore elit velit velit id exercitation excepteur veniam reprehenderit sint nulla duis ad incididunt cillum in in labore laboris magna esse.</p>',
    },
    {
        id          : '9d3f0e7f-dcbd-4e56-a5e8-87b8154e9edf',
        customer_picture : 'assets/images/avatars/male-02.jpg',
        status      : 'Awaiting',
        name        : 'Kevin Jimenez',
        customer    : 'Vicente Gomez',
        companyId   : 'a7806ced-03f1-4197-8b30-00bdd4243662',
        pass_date   : '1988-05-26T12:00:00.000Z',
        address     : '943 Adler Place, Hamilton, South Dakota, PO5592',
        notes       : '<p>Est amet in adipisicing ex excepteur ullamco est lorem adipisicing veniam reprehenderit elit commodo cillum commodo eu officia fugiat id reprehenderit sunt mollit eiusmod dolor fugiat ad do esse aliquip.</p><p>Mollit amet adipisicing enim est est commodo sint et eu nulla in laboris ipsum aliqua elit aliqua adipisicing ea nulla nulla consectetur velit laborum labore ullamco eu sit consectetur velit.</p>',
    },
];
